from . import res_company
from . import res_partner
from . import res_users
from . import brand
from . import product
from . import category
from . import car_model
from . import order
from . import prediction