# Generated by Django 3.2.4 on 2022-07-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220719_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(default='A description', max_length=50),
            preserve_default=False,
        ),
    ]
