# Generated by Django 3.2.4 on 2022-07-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.SlugField(max_length=55)),
                ('frontend_type', models.CharField(choices=[('1', 'select'), ('2', 'radio'), ('3', 'text'), ('4', 'text_area')], default='1', max_length=2)),
                ('is_filterable', models.BooleanField(default=False)),
                ('is_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
