# Generated by Django 3.2.4 on 2022-07-19 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_attributevalues'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttributeValues',
            new_name='AttributeValue',
        ),
    ]
