# Generated by Django 3.2.4 on 2022-07-19 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='location',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
    ]
