# Generated by Django 3.2.4 on 2022-08-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='advert1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='advert2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='advert3',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='advert_status',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='advert_subscription',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='business_status',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='business_subscription',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='location',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
